/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mzsanford_cld_CompactLanguageDetector */

#ifndef _Included_com_mzsanford_cld_CompactLanguageDetector
#define _Included_com_mzsanford_cld_CompactLanguageDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mzsanford_cld_CompactLanguageDetector
 * Method:    detectLanguage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mzsanford_cld_CompactLanguageDetector_detectLanguage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mzsanford_cld_CompactLanguageDetector
 * Method:    detectLanguageDetails
 * Signature: (Ljava/lang/String;ZZZZLjava/lang/String;)Lcom/mzsanford/cld/LanguageDetectionResult;
 */
JNIEXPORT jobject JNICALL Java_com_mzsanford_cld_CompactLanguageDetector_detectLanguageDetails
  (JNIEnv *, jobject, jstring, jboolean, jboolean, jboolean, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
