/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mzsanford_cld_CompactLanguageDetector_LanguageDetectionResult_LanguageDetectionCandidate */

#ifndef _Included_com_mzsanford_cld_CompactLanguageDetector_LanguageDetectionResult_LanguageDetectionCandidate
#define _Included_com_mzsanford_cld_CompactLanguageDetector_LanguageDetectionResult_LanguageDetectionCandidate
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
