/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mzsanford_cld_CompactLanguageDetector_LanguageDetectionResult */

#ifndef _Included_com_mzsanford_cld_CompactLanguageDetector_LanguageDetectionResult
#define _Included_com_mzsanford_cld_CompactLanguageDetector_LanguageDetectionResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
