# Makefile.in generated by automake 1.10 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






pkgdatadir = $(datadir)/cld
pkglibdir = $(libdir)/cld
pkgincludedir = $(includedir)/cld
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i386-apple-darwin11.2.0
host_triplet = i386-apple-darwin11.2.0
subdir = .
DIST_COMMON = README $(am__configure_deps) $(baseinclude_HEADERS) \
	$(encinclude_HEADERS) $(encprotoinclude_HEADERS) \
	$(encwininclude_HEADERS) $(langinclude_HEADERS) \
	$(langprotoinclude_HEADERS) $(noinst_HEADERS) \
	$(pkginclude_HEADERS) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/cld.pc.in \
	$(top_srcdir)/configure AUTHORS COPYING ChangeLog INSTALL NEWS \
	TODO config.guess config.sub depcomp install-sh ltmain.sh \
	missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES = cld.pc
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
am__installdirs = "$(DESTDIR)$(pkglibdir)" "$(DESTDIR)$(pkgconfigdir)" \
	"$(DESTDIR)$(baseincludedir)" "$(DESTDIR)$(encincludedir)" \
	"$(DESTDIR)$(encprotoincludedir)" \
	"$(DESTDIR)$(encwinincludedir)" "$(DESTDIR)$(langincludedir)" \
	"$(DESTDIR)$(langprotoincludedir)" \
	"$(DESTDIR)$(pkgincludedir)"
pkglibLTLIBRARIES_INSTALL = $(INSTALL)
LTLIBRARIES = $(pkglib_LTLIBRARIES)
libcld_la_LIBADD =
am_libcld_la_OBJECTS = cldutil.lo cldutil_dbg_empty.lo \
	compact_lang_det.lo compact_lang_det_impl.lo ext_lang_enc.lo \
	getonescriptspan.lo letterscript_enum.lo tote.lo \
	cld_generated_score_quadchrome_0406.lo \
	compact_lang_det_generated_cjkbis_0.lo \
	compact_lang_det_generated_ctjkvz.lo \
	compact_lang_det_generated_deltaoctachrome.lo \
	compact_lang_det_generated_quadschrome.lo \
	cld_htmlutils_windows.lo cld_unilib_windows.lo \
	cld_utf8statetable.lo cld_utf8utils_windows.lo encodings.lo \
	languages.lo
libcld_la_OBJECTS = $(am_libcld_la_OBJECTS)
libcld_la_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(libcld_la_LDFLAGS) $(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libcld_la_SOURCES)
DIST_SOURCES = $(libcld_la_SOURCES)
pkgconfigDATA_INSTALL = $(INSTALL_DATA)
DATA = $(pkgconfig_DATA)
baseincludeHEADERS_INSTALL = $(INSTALL_HEADER)
encincludeHEADERS_INSTALL = $(INSTALL_HEADER)
encprotoincludeHEADERS_INSTALL = $(INSTALL_HEADER)
encwinincludeHEADERS_INSTALL = $(INSTALL_HEADER)
langincludeHEADERS_INSTALL = $(INSTALL_HEADER)
langprotoincludeHEADERS_INSTALL = $(INSTALL_HEADER)
pkgincludeHEADERS_INSTALL = $(INSTALL_HEADER)
HEADERS = $(baseinclude_HEADERS) $(encinclude_HEADERS) \
	$(encprotoinclude_HEADERS) $(encwininclude_HEADERS) \
	$(langinclude_HEADERS) $(langprotoinclude_HEADERS) \
	$(noinst_HEADERS) $(pkginclude_HEADERS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/mzsanfor/src/gcode/cld-2/missing --run aclocal-1.10
AMTAR = ${SHELL} /Users/mzsanfor/src/gcode/cld-2/missing --run tar
AR = ar
AS = as
AUTOCONF = ${SHELL} /Users/mzsanfor/src/gcode/cld-2/missing --run autoconf
AUTOHEADER = ${SHELL} /Users/mzsanfor/src/gcode/cld-2/missing --run autoheader
AUTOMAKE = ${SHELL} /Users/mzsanfor/src/gcode/cld-2/missing --run automake-1.10
AWK = awk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"Compact\ Language\ Detector\" -DPACKAGE_TARNAME=\"cld\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"Compact\ Language\ Detector\ 0.1\" -DPACKAGE_BUGREPORT=\"matt@mzsanford.com\" -DPACKAGE=\"cld\" -DVERSION=\"0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\"
DEPDIR = .deps
DLLTOOL = dlltool
DSYMUTIL = dsymutil
DUMPBIN = 
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
FGREP = /usr/bin/grep -F
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = lipo
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /Users/mzsanfor/src/gcode/cld-2/missing --run makeinfo
MKDIR_P = ./install-sh -c -d
NM = /usr/bin/nm
NMEDIT = nmedit
OBJDUMP = objdump
OBJEXT = o
OTOOL = otool
OTOOL64 = :
PACKAGE = cld
PACKAGE_BUGREPORT = matt@mzsanford.com
PACKAGE_NAME = Compact Language Detector
PACKAGE_STRING = Compact Language Detector 0.1
PACKAGE_TARNAME = cld
PACKAGE_VERSION = 0.1
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 0.1
abs_builddir = /Users/mzsanfor/src/gcode/cld-2
abs_srcdir = /Users/mzsanfor/src/gcode/cld-2
abs_top_builddir = /Users/mzsanfor/src/gcode/cld-2
abs_top_srcdir = /Users/mzsanfor/src/gcode/cld-2
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i386-apple-darwin11.2.0
build_alias = 
build_cpu = i386
build_os = darwin11.2.0
build_vendor = apple
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i386-apple-darwin11.2.0
host_alias = 
host_cpu = i386
host_os = darwin11.2.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /Users/mzsanfor/src/gcode/cld-2/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(top_builddir)/./install-sh -c -d
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = gnu
AM_CPPFLAGS = -I. -Ibase -DCLD_WINDOWS
pkglib_LTLIBRARIES = libcld.la 
pkginclude_HEADERS = encodings/compact_lang_det/*.h
langincludedir = $(includedir)/cld/languages/public
langinclude_HEADERS = languages/public/*.h
langprotoincludedir = $(includedir)/cld/languages/proto
langprotoinclude_HEADERS = languages/proto/*.h
encincludedir = $(includedir)/cld/encodings/compact_lang_det
encinclude_HEADERS = encodings/compact_lang_det/*.h
encwinincludedir = $(includedir)/cld/encodings/compact_lang_det/win
encwininclude_HEADERS = encodings/compact_lang_det/win/*.h
encprotoincludedir = $(includedir)/cld/encodings/proto
encprotoinclude_HEADERS = encodings/proto/*.h
baseincludedir = $(includedir)/cld/base
baseinclude_HEADERS = base/*.h
noinst_HEADERS = 
libcld_la_SOURCES = encodings/compact_lang_det/cldutil.cc \
	encodings/compact_lang_det/cldutil_dbg_empty.cc \
	encodings/compact_lang_det/compact_lang_det.cc \
	encodings/compact_lang_det/compact_lang_det_impl.cc \
	encodings/compact_lang_det/ext_lang_enc.cc \
	encodings/compact_lang_det/getonescriptspan.cc \
	encodings/compact_lang_det/letterscript_enum.cc \
	encodings/compact_lang_det/tote.cc \
	encodings/compact_lang_det/generated/cld_generated_score_quadchrome_0406.cc \
	encodings/compact_lang_det/generated/compact_lang_det_generated_cjkbis_0.cc \
	encodings/compact_lang_det/generated/compact_lang_det_generated_ctjkvz.cc \
	encodings/compact_lang_det/generated/compact_lang_det_generated_deltaoctachrome.cc \
	encodings/compact_lang_det/generated/compact_lang_det_generated_quadschrome.cc \
	encodings/compact_lang_det/win/cld_htmlutils_windows.cc \
	encodings/compact_lang_det/win/cld_unilib_windows.cc \
	encodings/compact_lang_det/win/cld_utf8statetable.cc \
	encodings/compact_lang_det/win/cld_utf8utils_windows.cc \
	encodings/internal/encodings.cc \
	languages/internal/languages.cc
libcld_la_LDFLAGS = -version 0:1:0 
pkgconfigdir = $(libdir)/pkgconfig
pkgconfig_DATA = cld.pc
all: all-am

.SUFFIXES:
.SUFFIXES: .cc .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu '; \
	      cd $(srcdir) && $(AUTOMAKE) --gnu  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
cld.pc: $(top_builddir)/config.status $(srcdir)/cld.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-pkglibLTLIBRARIES: $(pkglib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(pkglibdir)" || $(MKDIR_P) "$(DESTDIR)$(pkglibdir)"
	@list='$(pkglib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f=$(am__strip_dir) \
	    echo " $(LIBTOOL) --mode=install $(pkglibLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) '$$p' '$(DESTDIR)$(pkglibdir)/$$f'"; \
	    $(LIBTOOL) --mode=install $(pkglibLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) "$$p" "$(DESTDIR)$(pkglibdir)/$$f"; \
	  else :; fi; \
	done

uninstall-pkglibLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(pkglib_LTLIBRARIES)'; for p in $$list; do \
	  p=$(am__strip_dir) \
	  echo " $(LIBTOOL) --mode=uninstall rm -f '$(DESTDIR)$(pkglibdir)/$$p'"; \
	  $(LIBTOOL) --mode=uninstall rm -f "$(DESTDIR)$(pkglibdir)/$$p"; \
	done

clean-pkglibLTLIBRARIES:
	-test -z "$(pkglib_LTLIBRARIES)" || rm -f $(pkglib_LTLIBRARIES)
	@list='$(pkglib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libcld.la: $(libcld_la_OBJECTS) $(libcld_la_DEPENDENCIES) 
	$(libcld_la_LINK) -rpath $(pkglibdir) $(libcld_la_OBJECTS) $(libcld_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/cld_generated_score_quadchrome_0406.Plo
include ./$(DEPDIR)/cld_htmlutils_windows.Plo
include ./$(DEPDIR)/cld_unilib_windows.Plo
include ./$(DEPDIR)/cld_utf8statetable.Plo
include ./$(DEPDIR)/cld_utf8utils_windows.Plo
include ./$(DEPDIR)/cldutil.Plo
include ./$(DEPDIR)/cldutil_dbg_empty.Plo
include ./$(DEPDIR)/compact_lang_det.Plo
include ./$(DEPDIR)/compact_lang_det_generated_cjkbis_0.Plo
include ./$(DEPDIR)/compact_lang_det_generated_ctjkvz.Plo
include ./$(DEPDIR)/compact_lang_det_generated_deltaoctachrome.Plo
include ./$(DEPDIR)/compact_lang_det_generated_quadschrome.Plo
include ./$(DEPDIR)/compact_lang_det_impl.Plo
include ./$(DEPDIR)/encodings.Plo
include ./$(DEPDIR)/ext_lang_enc.Plo
include ./$(DEPDIR)/getonescriptspan.Plo
include ./$(DEPDIR)/languages.Plo
include ./$(DEPDIR)/letterscript_enum.Plo
include ./$(DEPDIR)/tote.Plo

.cc.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cc.lo:
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

cldutil.lo: encodings/compact_lang_det/cldutil.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT cldutil.lo -MD -MP -MF $(DEPDIR)/cldutil.Tpo -c -o cldutil.lo `test -f 'encodings/compact_lang_det/cldutil.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/cldutil.cc
	mv -f $(DEPDIR)/cldutil.Tpo $(DEPDIR)/cldutil.Plo
#	source='encodings/compact_lang_det/cldutil.cc' object='cldutil.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o cldutil.lo `test -f 'encodings/compact_lang_det/cldutil.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/cldutil.cc

cldutil_dbg_empty.lo: encodings/compact_lang_det/cldutil_dbg_empty.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT cldutil_dbg_empty.lo -MD -MP -MF $(DEPDIR)/cldutil_dbg_empty.Tpo -c -o cldutil_dbg_empty.lo `test -f 'encodings/compact_lang_det/cldutil_dbg_empty.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/cldutil_dbg_empty.cc
	mv -f $(DEPDIR)/cldutil_dbg_empty.Tpo $(DEPDIR)/cldutil_dbg_empty.Plo
#	source='encodings/compact_lang_det/cldutil_dbg_empty.cc' object='cldutil_dbg_empty.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o cldutil_dbg_empty.lo `test -f 'encodings/compact_lang_det/cldutil_dbg_empty.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/cldutil_dbg_empty.cc

compact_lang_det.lo: encodings/compact_lang_det/compact_lang_det.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT compact_lang_det.lo -MD -MP -MF $(DEPDIR)/compact_lang_det.Tpo -c -o compact_lang_det.lo `test -f 'encodings/compact_lang_det/compact_lang_det.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/compact_lang_det.cc
	mv -f $(DEPDIR)/compact_lang_det.Tpo $(DEPDIR)/compact_lang_det.Plo
#	source='encodings/compact_lang_det/compact_lang_det.cc' object='compact_lang_det.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o compact_lang_det.lo `test -f 'encodings/compact_lang_det/compact_lang_det.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/compact_lang_det.cc

compact_lang_det_impl.lo: encodings/compact_lang_det/compact_lang_det_impl.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT compact_lang_det_impl.lo -MD -MP -MF $(DEPDIR)/compact_lang_det_impl.Tpo -c -o compact_lang_det_impl.lo `test -f 'encodings/compact_lang_det/compact_lang_det_impl.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/compact_lang_det_impl.cc
	mv -f $(DEPDIR)/compact_lang_det_impl.Tpo $(DEPDIR)/compact_lang_det_impl.Plo
#	source='encodings/compact_lang_det/compact_lang_det_impl.cc' object='compact_lang_det_impl.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o compact_lang_det_impl.lo `test -f 'encodings/compact_lang_det/compact_lang_det_impl.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/compact_lang_det_impl.cc

ext_lang_enc.lo: encodings/compact_lang_det/ext_lang_enc.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ext_lang_enc.lo -MD -MP -MF $(DEPDIR)/ext_lang_enc.Tpo -c -o ext_lang_enc.lo `test -f 'encodings/compact_lang_det/ext_lang_enc.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/ext_lang_enc.cc
	mv -f $(DEPDIR)/ext_lang_enc.Tpo $(DEPDIR)/ext_lang_enc.Plo
#	source='encodings/compact_lang_det/ext_lang_enc.cc' object='ext_lang_enc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ext_lang_enc.lo `test -f 'encodings/compact_lang_det/ext_lang_enc.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/ext_lang_enc.cc

getonescriptspan.lo: encodings/compact_lang_det/getonescriptspan.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT getonescriptspan.lo -MD -MP -MF $(DEPDIR)/getonescriptspan.Tpo -c -o getonescriptspan.lo `test -f 'encodings/compact_lang_det/getonescriptspan.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/getonescriptspan.cc
	mv -f $(DEPDIR)/getonescriptspan.Tpo $(DEPDIR)/getonescriptspan.Plo
#	source='encodings/compact_lang_det/getonescriptspan.cc' object='getonescriptspan.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o getonescriptspan.lo `test -f 'encodings/compact_lang_det/getonescriptspan.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/getonescriptspan.cc

letterscript_enum.lo: encodings/compact_lang_det/letterscript_enum.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT letterscript_enum.lo -MD -MP -MF $(DEPDIR)/letterscript_enum.Tpo -c -o letterscript_enum.lo `test -f 'encodings/compact_lang_det/letterscript_enum.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/letterscript_enum.cc
	mv -f $(DEPDIR)/letterscript_enum.Tpo $(DEPDIR)/letterscript_enum.Plo
#	source='encodings/compact_lang_det/letterscript_enum.cc' object='letterscript_enum.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o letterscript_enum.lo `test -f 'encodings/compact_lang_det/letterscript_enum.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/letterscript_enum.cc

tote.lo: encodings/compact_lang_det/tote.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT tote.lo -MD -MP -MF $(DEPDIR)/tote.Tpo -c -o tote.lo `test -f 'encodings/compact_lang_det/tote.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/tote.cc
	mv -f $(DEPDIR)/tote.Tpo $(DEPDIR)/tote.Plo
#	source='encodings/compact_lang_det/tote.cc' object='tote.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tote.lo `test -f 'encodings/compact_lang_det/tote.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/tote.cc

cld_generated_score_quadchrome_0406.lo: encodings/compact_lang_det/generated/cld_generated_score_quadchrome_0406.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT cld_generated_score_quadchrome_0406.lo -MD -MP -MF $(DEPDIR)/cld_generated_score_quadchrome_0406.Tpo -c -o cld_generated_score_quadchrome_0406.lo `test -f 'encodings/compact_lang_det/generated/cld_generated_score_quadchrome_0406.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/generated/cld_generated_score_quadchrome_0406.cc
	mv -f $(DEPDIR)/cld_generated_score_quadchrome_0406.Tpo $(DEPDIR)/cld_generated_score_quadchrome_0406.Plo
#	source='encodings/compact_lang_det/generated/cld_generated_score_quadchrome_0406.cc' object='cld_generated_score_quadchrome_0406.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o cld_generated_score_quadchrome_0406.lo `test -f 'encodings/compact_lang_det/generated/cld_generated_score_quadchrome_0406.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/generated/cld_generated_score_quadchrome_0406.cc

compact_lang_det_generated_cjkbis_0.lo: encodings/compact_lang_det/generated/compact_lang_det_generated_cjkbis_0.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT compact_lang_det_generated_cjkbis_0.lo -MD -MP -MF $(DEPDIR)/compact_lang_det_generated_cjkbis_0.Tpo -c -o compact_lang_det_generated_cjkbis_0.lo `test -f 'encodings/compact_lang_det/generated/compact_lang_det_generated_cjkbis_0.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/generated/compact_lang_det_generated_cjkbis_0.cc
	mv -f $(DEPDIR)/compact_lang_det_generated_cjkbis_0.Tpo $(DEPDIR)/compact_lang_det_generated_cjkbis_0.Plo
#	source='encodings/compact_lang_det/generated/compact_lang_det_generated_cjkbis_0.cc' object='compact_lang_det_generated_cjkbis_0.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o compact_lang_det_generated_cjkbis_0.lo `test -f 'encodings/compact_lang_det/generated/compact_lang_det_generated_cjkbis_0.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/generated/compact_lang_det_generated_cjkbis_0.cc

compact_lang_det_generated_ctjkvz.lo: encodings/compact_lang_det/generated/compact_lang_det_generated_ctjkvz.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT compact_lang_det_generated_ctjkvz.lo -MD -MP -MF $(DEPDIR)/compact_lang_det_generated_ctjkvz.Tpo -c -o compact_lang_det_generated_ctjkvz.lo `test -f 'encodings/compact_lang_det/generated/compact_lang_det_generated_ctjkvz.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/generated/compact_lang_det_generated_ctjkvz.cc
	mv -f $(DEPDIR)/compact_lang_det_generated_ctjkvz.Tpo $(DEPDIR)/compact_lang_det_generated_ctjkvz.Plo
#	source='encodings/compact_lang_det/generated/compact_lang_det_generated_ctjkvz.cc' object='compact_lang_det_generated_ctjkvz.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o compact_lang_det_generated_ctjkvz.lo `test -f 'encodings/compact_lang_det/generated/compact_lang_det_generated_ctjkvz.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/generated/compact_lang_det_generated_ctjkvz.cc

compact_lang_det_generated_deltaoctachrome.lo: encodings/compact_lang_det/generated/compact_lang_det_generated_deltaoctachrome.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT compact_lang_det_generated_deltaoctachrome.lo -MD -MP -MF $(DEPDIR)/compact_lang_det_generated_deltaoctachrome.Tpo -c -o compact_lang_det_generated_deltaoctachrome.lo `test -f 'encodings/compact_lang_det/generated/compact_lang_det_generated_deltaoctachrome.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/generated/compact_lang_det_generated_deltaoctachrome.cc
	mv -f $(DEPDIR)/compact_lang_det_generated_deltaoctachrome.Tpo $(DEPDIR)/compact_lang_det_generated_deltaoctachrome.Plo
#	source='encodings/compact_lang_det/generated/compact_lang_det_generated_deltaoctachrome.cc' object='compact_lang_det_generated_deltaoctachrome.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o compact_lang_det_generated_deltaoctachrome.lo `test -f 'encodings/compact_lang_det/generated/compact_lang_det_generated_deltaoctachrome.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/generated/compact_lang_det_generated_deltaoctachrome.cc

compact_lang_det_generated_quadschrome.lo: encodings/compact_lang_det/generated/compact_lang_det_generated_quadschrome.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT compact_lang_det_generated_quadschrome.lo -MD -MP -MF $(DEPDIR)/compact_lang_det_generated_quadschrome.Tpo -c -o compact_lang_det_generated_quadschrome.lo `test -f 'encodings/compact_lang_det/generated/compact_lang_det_generated_quadschrome.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/generated/compact_lang_det_generated_quadschrome.cc
	mv -f $(DEPDIR)/compact_lang_det_generated_quadschrome.Tpo $(DEPDIR)/compact_lang_det_generated_quadschrome.Plo
#	source='encodings/compact_lang_det/generated/compact_lang_det_generated_quadschrome.cc' object='compact_lang_det_generated_quadschrome.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o compact_lang_det_generated_quadschrome.lo `test -f 'encodings/compact_lang_det/generated/compact_lang_det_generated_quadschrome.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/generated/compact_lang_det_generated_quadschrome.cc

cld_htmlutils_windows.lo: encodings/compact_lang_det/win/cld_htmlutils_windows.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT cld_htmlutils_windows.lo -MD -MP -MF $(DEPDIR)/cld_htmlutils_windows.Tpo -c -o cld_htmlutils_windows.lo `test -f 'encodings/compact_lang_det/win/cld_htmlutils_windows.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/win/cld_htmlutils_windows.cc
	mv -f $(DEPDIR)/cld_htmlutils_windows.Tpo $(DEPDIR)/cld_htmlutils_windows.Plo
#	source='encodings/compact_lang_det/win/cld_htmlutils_windows.cc' object='cld_htmlutils_windows.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o cld_htmlutils_windows.lo `test -f 'encodings/compact_lang_det/win/cld_htmlutils_windows.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/win/cld_htmlutils_windows.cc

cld_unilib_windows.lo: encodings/compact_lang_det/win/cld_unilib_windows.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT cld_unilib_windows.lo -MD -MP -MF $(DEPDIR)/cld_unilib_windows.Tpo -c -o cld_unilib_windows.lo `test -f 'encodings/compact_lang_det/win/cld_unilib_windows.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/win/cld_unilib_windows.cc
	mv -f $(DEPDIR)/cld_unilib_windows.Tpo $(DEPDIR)/cld_unilib_windows.Plo
#	source='encodings/compact_lang_det/win/cld_unilib_windows.cc' object='cld_unilib_windows.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o cld_unilib_windows.lo `test -f 'encodings/compact_lang_det/win/cld_unilib_windows.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/win/cld_unilib_windows.cc

cld_utf8statetable.lo: encodings/compact_lang_det/win/cld_utf8statetable.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT cld_utf8statetable.lo -MD -MP -MF $(DEPDIR)/cld_utf8statetable.Tpo -c -o cld_utf8statetable.lo `test -f 'encodings/compact_lang_det/win/cld_utf8statetable.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/win/cld_utf8statetable.cc
	mv -f $(DEPDIR)/cld_utf8statetable.Tpo $(DEPDIR)/cld_utf8statetable.Plo
#	source='encodings/compact_lang_det/win/cld_utf8statetable.cc' object='cld_utf8statetable.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o cld_utf8statetable.lo `test -f 'encodings/compact_lang_det/win/cld_utf8statetable.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/win/cld_utf8statetable.cc

cld_utf8utils_windows.lo: encodings/compact_lang_det/win/cld_utf8utils_windows.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT cld_utf8utils_windows.lo -MD -MP -MF $(DEPDIR)/cld_utf8utils_windows.Tpo -c -o cld_utf8utils_windows.lo `test -f 'encodings/compact_lang_det/win/cld_utf8utils_windows.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/win/cld_utf8utils_windows.cc
	mv -f $(DEPDIR)/cld_utf8utils_windows.Tpo $(DEPDIR)/cld_utf8utils_windows.Plo
#	source='encodings/compact_lang_det/win/cld_utf8utils_windows.cc' object='cld_utf8utils_windows.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o cld_utf8utils_windows.lo `test -f 'encodings/compact_lang_det/win/cld_utf8utils_windows.cc' || echo '$(srcdir)/'`encodings/compact_lang_det/win/cld_utf8utils_windows.cc

encodings.lo: encodings/internal/encodings.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT encodings.lo -MD -MP -MF $(DEPDIR)/encodings.Tpo -c -o encodings.lo `test -f 'encodings/internal/encodings.cc' || echo '$(srcdir)/'`encodings/internal/encodings.cc
	mv -f $(DEPDIR)/encodings.Tpo $(DEPDIR)/encodings.Plo
#	source='encodings/internal/encodings.cc' object='encodings.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o encodings.lo `test -f 'encodings/internal/encodings.cc' || echo '$(srcdir)/'`encodings/internal/encodings.cc

languages.lo: languages/internal/languages.cc
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT languages.lo -MD -MP -MF $(DEPDIR)/languages.Tpo -c -o languages.lo `test -f 'languages/internal/languages.cc' || echo '$(srcdir)/'`languages/internal/languages.cc
	mv -f $(DEPDIR)/languages.Tpo $(DEPDIR)/languages.Plo
#	source='languages/internal/languages.cc' object='languages.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o languages.lo `test -f 'languages/internal/languages.cc' || echo '$(srcdir)/'`languages/internal/languages.cc

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(pkgconfigdir)" || $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)"
	@list='$(pkgconfig_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(pkgconfigDATA_INSTALL) '$$d$$p' '$(DESTDIR)$(pkgconfigdir)/$$f'"; \
	  $(pkgconfigDATA_INSTALL) "$$d$$p" "$(DESTDIR)$(pkgconfigdir)/$$f"; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(pkgconfigdir)/$$f'"; \
	  rm -f "$(DESTDIR)$(pkgconfigdir)/$$f"; \
	done
install-baseincludeHEADERS: $(baseinclude_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(baseincludedir)" || $(MKDIR_P) "$(DESTDIR)$(baseincludedir)"
	@list='$(baseinclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(baseincludeHEADERS_INSTALL) '$$d$$p' '$(DESTDIR)$(baseincludedir)/$$f'"; \
	  $(baseincludeHEADERS_INSTALL) "$$d$$p" "$(DESTDIR)$(baseincludedir)/$$f"; \
	done

uninstall-baseincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(baseinclude_HEADERS)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(baseincludedir)/$$f'"; \
	  rm -f "$(DESTDIR)$(baseincludedir)/$$f"; \
	done
install-encincludeHEADERS: $(encinclude_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(encincludedir)" || $(MKDIR_P) "$(DESTDIR)$(encincludedir)"
	@list='$(encinclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(encincludeHEADERS_INSTALL) '$$d$$p' '$(DESTDIR)$(encincludedir)/$$f'"; \
	  $(encincludeHEADERS_INSTALL) "$$d$$p" "$(DESTDIR)$(encincludedir)/$$f"; \
	done

uninstall-encincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(encinclude_HEADERS)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(encincludedir)/$$f'"; \
	  rm -f "$(DESTDIR)$(encincludedir)/$$f"; \
	done
install-encprotoincludeHEADERS: $(encprotoinclude_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(encprotoincludedir)" || $(MKDIR_P) "$(DESTDIR)$(encprotoincludedir)"
	@list='$(encprotoinclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(encprotoincludeHEADERS_INSTALL) '$$d$$p' '$(DESTDIR)$(encprotoincludedir)/$$f'"; \
	  $(encprotoincludeHEADERS_INSTALL) "$$d$$p" "$(DESTDIR)$(encprotoincludedir)/$$f"; \
	done

uninstall-encprotoincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(encprotoinclude_HEADERS)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(encprotoincludedir)/$$f'"; \
	  rm -f "$(DESTDIR)$(encprotoincludedir)/$$f"; \
	done
install-encwinincludeHEADERS: $(encwininclude_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(encwinincludedir)" || $(MKDIR_P) "$(DESTDIR)$(encwinincludedir)"
	@list='$(encwininclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(encwinincludeHEADERS_INSTALL) '$$d$$p' '$(DESTDIR)$(encwinincludedir)/$$f'"; \
	  $(encwinincludeHEADERS_INSTALL) "$$d$$p" "$(DESTDIR)$(encwinincludedir)/$$f"; \
	done

uninstall-encwinincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(encwininclude_HEADERS)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(encwinincludedir)/$$f'"; \
	  rm -f "$(DESTDIR)$(encwinincludedir)/$$f"; \
	done
install-langincludeHEADERS: $(langinclude_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(langincludedir)" || $(MKDIR_P) "$(DESTDIR)$(langincludedir)"
	@list='$(langinclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(langincludeHEADERS_INSTALL) '$$d$$p' '$(DESTDIR)$(langincludedir)/$$f'"; \
	  $(langincludeHEADERS_INSTALL) "$$d$$p" "$(DESTDIR)$(langincludedir)/$$f"; \
	done

uninstall-langincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(langinclude_HEADERS)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(langincludedir)/$$f'"; \
	  rm -f "$(DESTDIR)$(langincludedir)/$$f"; \
	done
install-langprotoincludeHEADERS: $(langprotoinclude_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(langprotoincludedir)" || $(MKDIR_P) "$(DESTDIR)$(langprotoincludedir)"
	@list='$(langprotoinclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(langprotoincludeHEADERS_INSTALL) '$$d$$p' '$(DESTDIR)$(langprotoincludedir)/$$f'"; \
	  $(langprotoincludeHEADERS_INSTALL) "$$d$$p" "$(DESTDIR)$(langprotoincludedir)/$$f"; \
	done

uninstall-langprotoincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(langprotoinclude_HEADERS)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(langprotoincludedir)/$$f'"; \
	  rm -f "$(DESTDIR)$(langprotoincludedir)/$$f"; \
	done
install-pkgincludeHEADERS: $(pkginclude_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(pkgincludedir)" || $(MKDIR_P) "$(DESTDIR)$(pkgincludedir)"
	@list='$(pkginclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(pkgincludeHEADERS_INSTALL) '$$d$$p' '$(DESTDIR)$(pkgincludedir)/$$f'"; \
	  $(pkgincludeHEADERS_INSTALL) "$$d$$p" "$(DESTDIR)$(pkgincludedir)/$$f"; \
	done

uninstall-pkgincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(pkginclude_HEADERS)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(pkgincludedir)/$$f'"; \
	  rm -f "$(DESTDIR)$(pkgincludedir)/$$f"; \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d $(distdir) || mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -755 -exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(DATA) $(HEADERS)
installdirs:
	for dir in "$(DESTDIR)$(pkglibdir)" "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(baseincludedir)" "$(DESTDIR)$(encincludedir)" "$(DESTDIR)$(encprotoincludedir)" "$(DESTDIR)$(encwinincludedir)" "$(DESTDIR)$(langincludedir)" "$(DESTDIR)$(langprotoincludedir)" "$(DESTDIR)$(pkgincludedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool clean-pkglibLTLIBRARIES \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am: install-baseincludeHEADERS install-encincludeHEADERS \
	install-encprotoincludeHEADERS install-encwinincludeHEADERS \
	install-langincludeHEADERS install-langprotoincludeHEADERS \
	install-pkgconfigDATA install-pkgincludeHEADERS

install-dvi: install-dvi-am

install-exec-am: install-pkglibLTLIBRARIES

install-html: install-html-am

install-info: install-info-am

install-man:

install-pdf: install-pdf-am

install-ps: install-ps-am

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-baseincludeHEADERS uninstall-encincludeHEADERS \
	uninstall-encprotoincludeHEADERS \
	uninstall-encwinincludeHEADERS uninstall-langincludeHEADERS \
	uninstall-langprotoincludeHEADERS uninstall-pkgconfigDATA \
	uninstall-pkgincludeHEADERS uninstall-pkglibLTLIBRARIES

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-generic clean-libtool clean-pkglibLTLIBRARIES ctags dist \
	dist-all dist-bzip2 dist-gzip dist-shar dist-tarZ dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-libtool distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-baseincludeHEADERS install-data \
	install-data-am install-dvi install-dvi-am \
	install-encincludeHEADERS install-encprotoincludeHEADERS \
	install-encwinincludeHEADERS install-exec install-exec-am \
	install-html install-html-am install-info install-info-am \
	install-langincludeHEADERS install-langprotoincludeHEADERS \
	install-man install-pdf install-pdf-am install-pkgconfigDATA \
	install-pkgincludeHEADERS install-pkglibLTLIBRARIES install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-baseincludeHEADERS \
	uninstall-encincludeHEADERS uninstall-encprotoincludeHEADERS \
	uninstall-encwinincludeHEADERS uninstall-langincludeHEADERS \
	uninstall-langprotoincludeHEADERS uninstall-pkgconfigDATA \
	uninstall-pkgincludeHEADERS uninstall-pkglibLTLIBRARIES


%Dictionary.cc %Dictionary.h:$(pkginclude_HEADERS) %LinkDef.hh
	@ROOTCINT@ -f $*.cc -c $(AM_CPPLFAGS) $(INCLUDES) $^ 
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
